class Operadora(db.Model):
    # ...existing code...
    @staticmethod
    def listar_ativas():
        return db.session.query(Operadora).filter(Operadora.status_ativo == True).all()
    # ...existing code...
